export type { PipelineReportDto } from './Dashboard/Pipeline/PipelineReportDto';
export type { SalesPipelineReportRowDto } from './Dashboard/Pipeline/SalesPipelineReportRowDto';
export type { DatePeriodDto } from './DatePeriodDto';
export type { EntitySummaryReport } from './EntitySummary/EntitySummaryReport';
export type { EntitySummaryValue } from './EntitySummary/EntitySummaryValue';
export type { ReportFilter } from './ReportFilter';
export type { ComparativeReportCellDto } from './Reports/Comparative/ComparativeReportCellDto';
export type { ComparativeReportDto } from './Reports/Comparative/ComparativeReportDto';
export { ComparativeReportFilterDto } from './Reports/Comparative/ComparativeReportFilterDto';
export type { ComparativeReportRowDto } from './Reports/Comparative/ComparativeReportRowDto';
export type { ComparativeReportValueDto } from './Reports/Comparative/ComparativeReportValueDto';
export type { CustomerReportDto } from './Reports/Customer/CustomerReportDto';
export type { CustomerReportFieldDto } from './Reports/Customer/CustomerReportFieldDto';
export type { CustomerReportFieldMetaDto } from './Reports/Customer/CustomerReportFieldMetaDto';
export { CustomerReportFilterDto } from './Reports/Customer/CustomerReportFilterDto';
export type { CustomerReportMetaDto } from './Reports/Customer/CustomerReportMetaDto';
export type { CustomerReportRowDto } from './Reports/Customer/CustomerReportRowDto';
export { CallReportBlockDto } from './Reports/General/CallReportBlockDto';
export type { GeneralReportDto } from './Reports/General/GeneralReportDto';
export type { GeneralReportEntityDto } from './Reports/General/GeneralReportEntityDto';
export { GeneralReportFieldDto } from './Reports/General/GeneralReportFieldDto';
export { GeneralReportFieldMetaDto } from './Reports/General/GeneralReportFieldMetaDto';
export type { GeneralReportFieldOptionMetaDto } from './Reports/General/GeneralReportFieldOptionMetaDto';
export { GeneralReportFieldValueDto } from './Reports/General/GeneralReportFieldValueDto';
export { GeneralReportFilterDto } from './Reports/General/GeneralReportFilterDto';
export { GeneralReportFilterVisibilityCallDto } from './Reports/General/GeneralReportFilterVisibilityCallDto';
export { GeneralReportFilterVisibilityDto } from './Reports/General/GeneralReportFilterVisibilityDto';
export { GeneralReportFilterVisibilityEntityDto } from './Reports/General/GeneralReportFilterVisibilityEntityDto';
export { GeneralReportFilterVisibilityFieldDto } from './Reports/General/GeneralReportFilterVisibilityFieldDto';
export { GeneralReportFilterVisibilityFieldOptionDto } from './Reports/General/GeneralReportFilterVisibilityFieldOptionDto';
export { GeneralReportFilterVisibilityFieldsDto } from './Reports/General/GeneralReportFilterVisibilityFieldsDto';
export { GeneralReportFilterVisibilityTaskDto } from './Reports/General/GeneralReportFilterVisibilityTaskDto';
export { GeneralReportMetaDto } from './Reports/General/GeneralReportMetaDto';
export { GeneralReportRowDto } from './Reports/General/GeneralReportRowDto';
export type { GeneralReportTaskDto } from './Reports/General/GeneralReportTaskDto';
export type { PossibleReportFilterDto } from './Reports/PossibleReportFilterDto';
export type { ProductsReportDto } from './Reports/Products/General/ProductsReportDto';
export { ProductsReportFilterDto } from './Reports/Products/General/ProductsReportFilterDto';
export type { ProductsReportRowDto } from './Reports/Products/General/ProductsReportRowDto';
export type { ProductsReportUserCellDto } from './Reports/Products/General/ProductsReportUserCellDto';
export type { ProjectEntitiesReportDto } from './Reports/Projects/ProjectEntitiesReportDto';
export { ProjectEntitiesReportFilterDto } from './Reports/Projects/ProjectEntitiesReportFilterDto';
export type { ProjectEntitiesReportMetaDto } from './Reports/Projects/ProjectEntitiesReportMetaDto';
export type { ProjectEntitiesReportRowDto } from './Reports/Projects/ProjectEntitiesReportRowDto';
export type { ProjectReportFieldDto } from './Reports/Projects/ProjectReportFieldDto';
export type { ProjectReportFieldMetaDto } from './Reports/Projects/ProjectReportFieldMetaDto';
export { ProjectTaskUserReportFilterDto } from './Reports/Projects/ProjectsReportFilterDto';
export type { ProjectTaskUserReportDto } from './Reports/Projects/ProjectTaskUserReportDto';
export type { ProjectTaskUserReportRowDto } from './Reports/Projects/ProjectTaskUserReportRowDto';
export type { ProjectTaskUserReportRowTotalDto } from './Reports/Projects/ProjectTaskUserReportRowTotalDto';
export { ScheduleReportFilterDto } from './Reports/Schedule/ScheduleReportFilterDto';
export type { CallHistoryReportDto } from './Reports/Telephony/CallHistoryReportDto';
export { CallHistoryReportFilterDto } from './Reports/Telephony/CallHistoryReportFilterDto';
export type { CallHistoryReportItemDto } from './Reports/Telephony/CallHistoryReportItemDto';
export type { TelephonyReportDto } from './Reports/Telephony/TelephonyReportDto';
export { TelephonyReportFilterDto } from './Reports/Telephony/TelephonyReportFilterDto';
export type { TelephonyReportRowDto } from './Reports/Telephony/TelephonyReportRowDto';
export type { SalesPlanDto } from './SalesPlanDto';
export type { SalesPlanProgressDto } from './SalesPlanProgressDto';
export type { SalesPlanReport } from './SalesPlanReport';
export type { SellersRatingReport } from './SellersRatingReport';
export type { TasksSummaryReport } from './TasksSummaryReport';
export type { TopSellersReport } from './TopSellersReport';
