export enum ExternalSystemCode {
  AIRTABLE = 'airtable',
  AMOCRM = 'amocrm',
  BITRIX = 'bitrix',
  EXCEL = 'excel',
  FACEBOOK = 'facebook',
  FRESHSALES = 'freshsales',
  HUBSPOT = 'hubspot',
  INSTAGRAM = 'instagram',
  LINKEDIN = 'linkedin',
  MICROSOFT = 'microsoft',
  MONDAY = 'monday',
  NOTION = 'notion',
  ORACLE = 'oracle',
  PIPEDRIVE = 'pipedrive',
  SALESFORCE = 'salesforce',
  SAP = 'sap',
  SUGARCRM = 'sugarcrm',
  TWITTER = 'twitter',
  ZENDESK = 'zendesk',
  ZOHO = 'zoho',
}
