interface ImportMetaEnv {
  readonly VITE_APP_NAME: string;
  readonly VITE_APP_URL: string;
  readonly VITE_APP_DEMO_EMAIL: string;
  readonly VITE_APP_LANGUAGES: string;
  readonly VITE_APP_LOGO: string;
  readonly VITE_BASE_API_URL: string;
  readonly VITE_BASE_API_KEY: string;
  readonly VITE_GTM_ID: string;
  readonly VITE_IP_REGISTRY_API_KEY: string;
  readonly VITE_APP_URL_TEMPLATE: string;
  readonly VITE_APP_RU_SEGMENT: string;

  readonly VITE_BILLING_PATH: string;
  readonly VITE_BILLING_SHOW_CREDIT_BUTTON;

  readonly VITE_BUILDER_HIDE_MAIN_MODULES: string;
  readonly VITE_BUILDER_HIDE_FORM_BUILDER: string;
  readonly VITE_BUILDER_HIDE_TELEPHONY: string;
  readonly VITE_BUILDER_HIDE_BPMN: string;
  readonly VITE_BUILDER_HIDE_MARKETING: string;
  readonly VITE_BUILDER_HIDE_FINANCES: string;

  readonly VITE_INTEGRATIONS_SHOW_1C: string;
  readonly VITE_INTEGRATIONS_SHOW_SALESFORCE: string;
  readonly VITE_INTEGRATIONS_SHOW_WAZZUP: string;
  readonly VITE_INTEGRATIONS_SHOW_FB_MESSENGER: string;
  readonly VITE_INTEGRATIONS_SHOW_TWILIO: string;
  readonly VITE_INTEGRATIONS_SHOW_PBX: string;
  readonly VITE_INTEGRATIONS_SHOW_RU_PBX_PROVIDERS: string;
  readonly VITE_INTEGRATIONS_SHOW_MAKE: string;
  readonly VITE_INTEGRATIONS_SHOW_APIX_DRIVE: string;
  readonly VITE_INTEGRATIONS_SHOW_ALBATO: string;

  readonly VITE_VOXIMPLANT_SHOW_TELEPHONY: string;
  readonly VITE_VOXIMPLANT_CONNECTION_NODE: string;
  readonly VITE_VOXIMPLANT_INTEGRATION_GUIDE_TYPE: string;

  readonly VITE_DOCUMENTS_SHOW_ORDER_FIELDS: string;

  readonly VITE_NEW_RELIC_ENABLED: string;
  readonly VITE_NEW_RELIC_ACCOUNT_ID: string;
  readonly VITE_NEW_RELIC_LICENSE_KEY: string;
  readonly VITE_NEW_RELIC_APPLICATION_ID: string;

  readonly VITE_REQUEST_BPMN_WORKSPACE_FORM_NAME_FIELD_ID: string;
  readonly VITE_REQUEST_BPMN_WORKSPACE_FORM_PHONE_FIELD_ID: string;
  readonly VITE_REQUEST_BPMN_WORKSPACE_FORM_EMAIL_FIELD_ID: string;
  readonly VITE_REQUEST_BPMN_WORKSPACE_FORM_DOMAIN_FIELD_ID: string;
  readonly VITE_REQUEST_BPMN_WORKSPACE_FORM_COMMENT_FIELD_ID: string;
  readonly VITE_SUBMIT_REQUEST_BPMN_WORKSPACE_FORM_URL: string;

  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_NAME_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_PHONE_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_EMAIL_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_DOMAIN_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_COMMENT_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_STORAGE_FIELD_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_TEN_GB_OPTION_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_ONE_HUNDRED_GB_OPTION_ID: string;
  readonly VITE_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_ONE_TB_OPTION_ID: string;
  readonly VITE_SUBMIT_REQUEST_ADDITIONAL_STORAGE_WORKSPACE_FORM_URL: string;

  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_NUMBER_OF_USERS_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_NAME_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_ITN_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_ADDRESS_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_CONTACT_NAME_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PHONE_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_EMAIL_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_SUBDOMAIN_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_INVOICE_ID_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_TOTAL_PRICE_FIELD_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_LTD_BUSINESS_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_LTD_ADVANCED_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_YEAR_BUSINESS_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_YEAR_ADVANCED_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_MONTH_BUSINESS_ID: string;
  readonly VITE_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_PLAN_MONTH_ADVANCED_ID: string;
  readonly VITE_SUBMIT_REQUEST_MYWORK_INVOICE_WORKSPACE_FORM_URL: string;

  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_NAME_FIELD_ID: string;
  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_PHONE_FIELD_ID: string;
  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_EMAIL_FIELD_ID: string;
  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_COMMENT_FIELD_ID: string;
  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_SUBDOMAIN_FIELD_ID: string;
  readonly VITE_REQUEST_SETUP_HEADLESS_FORM_URL: string;

  readonly VITE_DIRECTUS_PUBLIC_BASE_URL: string;
  readonly VITE_DIRECTUS_STATIC_TOKEN: string;

  readonly VITE_REACT_QUERY_DEVTOOLS_ENABLED: string;

  readonly VITE_AUTOMATION_HIDE_BPMN: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
