export enum ErrorCode {
  BAD_REQUEST = 'bad_request',
  BAD_CREDENTIALS = 'bad_credentials',
  EMAIL_OCCUPIED = 'email_occupied',
  INVALID_LOGIN_LINK = 'invalid_login_link',
  INVALID_TOKEN = 'invalid_token',
  INVALID_PHONE = 'invalid_phone',
  INVALID_SUBDOMAIN = 'invalid_subdomain',
  FORBIDDEN = 'forbidden',
  PERMISSION_NOT_VALID = 'permission_not_valid',
  TOKEN_NOT_PASSED = 'token_not_passed',
  NOT_FOUND = 'not_found',
  USER_NOT_ACTIVE = 'user_not_active',
  REQUIRED_FIELD_EMPTY = 'required_field_empty',
  FIELD_USED_IN_FORMULA = 'field.used_in_formula',
  ENTITY_TYPE_FIELD_USED_IN_FORMULA = 'entity_type.used_in_formula',
  FIELD_FORMULA_CIRCULAR_DEPENDENCY = 'field.formula_circular_dependency',
  AUTOMATION_PROCESS_ERROR = 'automation.process_error',
  DUPLICATE_SCHEDULER_APPOINTMENT = 'scheduler.appointment.day_limit',
  INTERSECT_SCHEDULER_APPOINTMENT = 'scheduler.appointment.intersection',
  INVALID_DOCUMENT_TEMPLATE = 'document.template.wrong_template',
  FIELD_DUPLICATE_NAME = 'field.duplicate_name',
}
